//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class endMatching
    {
        public int Id { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> WhoPaid { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Remark { get; set; }
        public bool IsCare { get; set; }
        public string EndPlace { get; set; }
        public int MatchingId { get; set; }
    
        public virtual matching matching { get; set; }
    }
}
