//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class helper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public helper()
        {
            this.matchingHelpers = new HashSet<matchingHelper>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public int Type { get; set; }
        public int WorkerId { get; set; }
        public int CityId { get; set; }
        public int SectorId { get; set; }
    
        public virtual city city { get; set; }
        public virtual worker worker { get; set; }
        public virtual sector sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matchingHelper> matchingHelpers { get; set; }
    }
}
