//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class matching
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public matching()
        {
            this.endMatchings = new HashSet<endMatching>();
            this.meetings = new HashSet<meeting>();
            this.matchingHelpers = new HashSet<matchingHelper>();
            this.matchingComments = new HashSet<matchingComment>();
        }
    
        public int Id { get; set; }
        public System.DateTime Createdate { get; set; }
        public string Remark { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int Status { get; set; }
        public int Level { get; set; }
        public string ReasonFail { get; set; }
        public Nullable<int> Precent { get; set; }
        public Nullable<int> CandidateFailId { get; set; }
        public string ReasonCandidateFail { get; set; }
        public string ReasonCandidateFeFail { get; set; }
        public int CandidateId { get; set; }
        public int CandidateFemaleId { get; set; }
        public int MatchmarkerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<endMatching> endMatchings { get; set; }
        public virtual matchmaker matchmaker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meeting> meetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matchingHelper> matchingHelpers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matchingComment> matchingComments { get; set; }
        public virtual candidate candidate { get; set; }
        public virtual candidate candidate1 { get; set; }
    }
}
