//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class matchmaker
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string MedicalProblem { get; set; }
        public Nullable<int> ChasidutId { get; set; }
        public Nullable<int> NumMatching { get; set; }
        public Nullable<int> ChildremMatchmaking { get; set; }
        public int HowSend { get; set; }
        public bool IsCommitment { get; set; }
        public bool IsAgreement { get; set; }
        public int Status { get; set; }
        public int CityId { get; set; }
        public int SectorId { get; set; }
        public int WorkerId { get; set; }
    
        public virtual city city { get; set; }
        public virtual sector sector { get; set; }
        public virtual worker worker { get; set; }
    }
}
