//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting
    {
        public int Id { get; set; }
        public System.DateTime DateMeeting { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Place { get; set; }
        public Nullable<System.TimeSpan> DuringTime { get; set; }
        public Nullable<int> NumMeeting { get; set; }
        public string Remark { get; set; }
        public int MatchingId { get; set; }
    
        public virtual matching matching { get; set; }
    }
}
