//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MazalTovEntities : DbContext
    {
        public MazalTovEntities()
            : base("name=MazalTovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<askPermssion> askPermssions { get; set; }
        public virtual DbSet<bank> banks { get; set; }
        public virtual DbSet<candidateComment> candidateComments { get; set; }
        public virtual DbSet<chasidut> chasiduts { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<contactu> contactus { get; set; }
        public virtual DbSet<endMatching> endMatchings { get; set; }
        public virtual DbSet<helper> helpers { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<infoCandidate> infoCandidates { get; set; }
        public virtual DbSet<matching> matchings { get; set; }
        public virtual DbSet<matchingHelper> matchingHelpers { get; set; }
        public virtual DbSet<matchmaker> matchmakers { get; set; }
        public virtual DbSet<meeting> meetings { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<permssion> permssions { get; set; }
        public virtual DbSet<Present> Presents { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<roleAction> roleActions { get; set; }
        public virtual DbSet<sector> sectors { get; set; }
        public virtual DbSet<worker> workers { get; set; }
        public virtual DbSet<workerAction> workerActions { get; set; }
        public virtual DbSet<matchingComment> matchingComments { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<halachot> halachots { get; set; }
        public virtual DbSet<remark> remarks { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<candidateFamily> candidateFamilies { get; set; }
        public virtual DbSet<candidate> candidates { get; set; }
        public virtual DbSet<married> marrieds { get; set; }
    }
}
