//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int FromMonth { get; set; }
        public int FromYear { get; set; }
        public decimal Sum { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public decimal TotalPrice { get; set; }
        public int Status { get; set; }
        public int WorkerId { get; set; }
    
        public virtual worker worker { get; set; }
    }
}
