//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Present
    {
        public int Id { get; set; }
        public System.DateTime EnterDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> NumHours { get; set; }
        public string Subject { get; set; }
        public int WorkerId { get; set; }
    
        public virtual worker worker { get; set; }
    }
}
