//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int Id { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public string Content { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> CandidateFeId { get; set; }
        public Nullable<bool> IsCanWithMark { get; set; }
        public Nullable<bool> IsCanFeWithMark { get; set; }
        public Nullable<bool> IsCanSecretMark { get; set; }
        public Nullable<bool> IsCanFeSecretMark { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> DateAnswer { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual candidate candidate { get; set; }
        public virtual candidate candidate1 { get; set; }
    }
}
