//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class roleAction
    {
        public int PermssionId { get; set; }
        public int RoleId { get; set; }
        public int Id { get; set; }
    
        public virtual permssion permssion { get; set; }
        public virtual role role { get; set; }
    }
}
