//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_bus
    {
        public int kav { get; set; }
        public int stationid { get; set; }
        public Nullable<int> orbit { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual station station { get; set; }
    }
}
